# Generated by Django 4.2.7 on 2023-12-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('MA', 'Manager'), ('QA', 'QA'), ('DEV', 'Developer')], default='DEV', max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(related_name='tasks', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('REV', 'Review'), ('WOR', 'Working'), ('AWAIT', 'Awaiting Release'), ('WAIT', 'Waiting QA')], default='OP', max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
